<footer class="panel-footer text-center">
    <?= date('Y')?> &COPY; <?= config('app_name')?>
</footer>
<script>var URLBASE = "<?= config('url_base') ?>";</script>
<script src="/assets/js/jquery.js"></script>
<script src="/assets/plugins/jQuery-Mask-Plugin/dist/jquery.mask.js"></script>
<script src="/assets/plugins/jquery-validation/dist/jquery.validate.js"></script>
<script src="/assets/plugins/jquery-validation/dist/additional-methods.js"></script>
<script src="/assets/js/script.js"></script>
</body>
</html>