<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="_token" content="<?= _token() ?>">
    <title><?= config('app_name') ?></title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<header class="panel-heading">
    <nav>
        <h1 class="logo"><a href="#" class="default-logo" title="<?= config('app_name') ?>"><?= config('app_name') ?></a></h1>
    </nav>
</header>